ALTER TABLE itsm.incidents ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE itsm.incidents ADD COLUMN IF NOT EXISTS severity TEXT NOT NULL DEFAULT 'P3';
ALTER TABLE itsm.incidents ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'OPEN';
