ALTER TABLE itsm.changes
  ADD COLUMN IF NOT EXISTS requested_by TEXT,
  ADD COLUMN IF NOT EXISTS approved_by TEXT,
  ADD COLUMN IF NOT EXISTS rejected_by TEXT,
  ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS rollback_plan TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS preview_command TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS change_window_start TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS change_window_end TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS implemented_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

UPDATE itsm.changes
SET status = CASE UPPER(status)
  WHEN 'PENDING_APPROVAL' THEN 'SUBMITTED'
  WHEN 'IN_PROGRESS' THEN 'IMPLEMENTED'
  WHEN 'COMPLETED' THEN 'REVIEWED'
  ELSE UPPER(status)
END
WHERE status IS NOT NULL;

ALTER TABLE itsm.changes DROP CONSTRAINT IF EXISTS changes_status_check;
ALTER TABLE itsm.changes
  ADD CONSTRAINT changes_status_check
  CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'REVIEWED'));
